### ISSUE TITLE
Uncaught TypeError: array_key_exists()

### ISSUE THREAD

**Issue by atanasantonov** [bobbingwide/wp-a2z#20]
Hi when trying to hit https://woocommerce.wp-a2z.org/oik_api/wc_order/add_order_note/ there was a fatal error:

Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /home/customer/www/bobbingwide.org.uk/public_html/wp-includes/block-supports/align.php:48

Hope that helps or at least to turn off error reporting.

Best,
Atanas

**Comment by bobbingwide** [comment]
thanks for reporting, I'll investigate. Seems to be a general problem for woocommerce.wp-a2z.org. I've temporarily deactivated WooCommerce on that subdomain.

**Comment by bobbingwide** [comment]
I didn't do anything other than to reactivate WooCommerce; the Fatal's gone away.

**Comment by atanasantonov** [comment]
Very strange.. Maybe it's a good idea to turn off the error reporting.
